name: gestor_flutter
description: Gestor de tratamientos médicos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Utilidades
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  flutter_local_notifications: ^14.1.1
  timezone: ^0.9.2
  
  cupertino_icons: ^1.0.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  provider: ^6.1.2
  image_picker: ^1.0.7        
  share_plus: ^7.2.1          
  flutter_sound: ^9.2.13+1    
  permission_handler: ^11.3.0 
  path_provider: ^2.1.2  
firebase_storage: ^11.0.0
flutter_sound: ^9.2.13
image_picker: ^1.0.4
share_plus: ^7.0.0    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
 # assets:
  #  - assets/images/
